In [1]:
import pandas as pd

In [2]:
xjx_1=[]
xjx_2=[]
ypw_1=[]
ypw_2=[]
users_1=[]
users_2=[]

with open('xjx_average1.txt',mode='r') as f:
    for lines in f:
        a=lines.strip()
        xjx_1.append(float(a))
        
with open('xjx_average2.txt',mode='r') as f:
    for lines in f:
        a=lines.strip()
        xjx_2.append(float(a))
        
with open('ypw_average1.txt',mode='r') as f:
    for lines in f:
        a=lines.strip()
        ypw_1.append(float(a))

with open('ypw_average2.txt',mode='r') as f:
    for lines in f:
        a=lines.strip()
        ypw_2.append(float(a))

# print(xjx_1,xjx_2,ypw_1,ypw_2)

with open('ypw_user.txt',mode='r') as f:
    for lines in f:
        a=lines.strip().split(',')
        users_1.append(a)
        
with open('xjx_user.txt',mode='r') as f:
    for lines in f:
        a=lines.strip().split(',')
        users_2.append(a)

# print(users_1,users_2)

# df=pd.DataFrame(columns=['name','age','gender','job','1st_average_rating','2nd_average_rating'])
df1=pd.DataFrame(columns=['name','age','gender','job'])
df2=pd.DataFrame(columns=['1st_average_rating'])
df3=pd.DataFrame(columns=['2nd_average_rating'])
for user in users_1:
    add={}
    add['name']=user[0]
    add['age']=user[1]
    add['gender']=user[2]
    add['job']=user[3]
    df1=df1.append(add,ignore_index=True)
for r1 in ypw_1:
    add={}
    add['1st_average_rating']=r1
    df2=df2.append(add,ignore_index=True)
for r1 in ypw_2:
    add={}
    add['2nd_average_rating']=r1
    df3=df3.append(add,ignore_index=True)
df_1=pd.concat([df1,df2,df3],axis=1)
df_1

<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:56: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-2-d62e2990e76b>:60: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)

  name age  gender            job 1st_average_rating 2nd_average_rating
0   a1  22    male  undergraduate                3.5           3.833333
1   a2  23    male  undergraduate                4.0           4.333333
2   a3  22    male  undergraduate           3.666667           4.666667
3   a4  21  female  undergraduate                3.0           3.833333
4   a5  22  female  undergraduate           3.833333           3.333333
5   a6  25    male       engineer           3.666667           4.333333
6   a7  22    male  undergraduate           3.333333           4.166667
7   a8  26    male   postgraduate           3.333333                4.5
8   a9  22  female  undergraduate           4.333333           4.166667
9  a10  24    male  undergraduate           4.166667           3.833333

In [3]:
df1=pd.DataFrame(columns=['name','age','gender','job'])
df2=pd.DataFrame(columns=['1st_average_rating'])
df3=pd.DataFrame(columns=['2nd_average_rating'])
for user in users_2:
    add={}
    add['name']=user[0]
    add['age']=user[1]
    add['gender']=user[2]
    add['job']=user[3]
    df1=df1.append(add,ignore_index=True)
for r1 in xjx_1:
    add={}
    add['1st_average_rating']=r1
    df2=df2.append(add,ignore_index=True)
for r1 in xjx_2:
    add={}
    add['2nd_average_rating']=r1
    df3=df3.append(add,ignore_index=True)
df_2=pd.concat([df1,df2,df3],axis=1)
df_2

<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=df1.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2=df2.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)
<ipython-input-3-5410a5514def>:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df3.append(add,ignore_index=True)

  name age gender      job 1st_average_rating 2nd_average_rating
0   b1  24   male  student           2.666667           3.666667
1   b2  24   male  student           2.333333           3.333333
2   b3  22   male  student           2.166667           3.666667
3   b4  23   male  student                3.0                3.0
4   b5  25   male  student                2.8                3.0
5   b6  26   male    clerk                4.0                3.0
6   b7  26   male    clerk           2.833333                2.4
7   b8  23   male  student                2.2           2.833333
8   b9  22   male  student                2.8                3.5
9  b10  24   male  student           3.166667           3.166667

In [4]:
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel

#Paired t-Test
ttest_rel(ypw_1,ypw_2)

Ttest_relResult(statistic=-2.256213140985701, pvalue=0.05048808610932411)

In [5]:
#Paired t-Test
ttest_rel(xjx_1,xjx_2)

Ttest_relResult(statistic=-1.5163382155771266, pvalue=0.16374083103228607)

In [6]:
#Two-sample t-Test
ttest_ind(ypw_1,xjx_1)

Ttest_indResult(statistic=4.1355477927363316, pvalue=0.0006211161195087347)